# Generated by Django 3.2.12 on 2022-03-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('tag', models.CharField(blank=True, choices=[(0, 'Oud'), (1, 'Guitar'), (2, 'Tabla')], max_length=50, null=True)),
            ],
        ),
    ]
