# Generated by Django 3.2.12 on 2022-03-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20220324_0748'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryImages',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
