# Generated by Django 3.2.12 on 2022-04-02 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_vendor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
