# Generated by Django 3.2.13 on 2022-05-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Shipping', 'Shipped'), ('Delivered', 'Delivered')], default='Processing', max_length=15),
        ),
        migrations.DeleteModel(
            name='VendorPayments',
        ),
    ]
