# Generated by Django 3.2.13 on 2022-05-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20220522_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='activate',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
