# Generated by Django 3.2.13 on 2022-05-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_product_activate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='homePageImage',
        ),
        migrations.AddField(
            model_name='category',
            name='BannerImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='BannerImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
