# Generated by Django 3.2.12 on 2022-04-07 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220407_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='comapny_name',
            new_name='company_name',
        ),
    ]
