# Generated by Django 3.2.13 on 2022-05-22 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_vendorpayments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorPayments',
        ),
    ]
