# Generated by Django 3.2.13 on 2022-05-22 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_vendorpayments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorpayments',
            old_name='payemnts',
            new_name='payments',
        ),
    ]
