# Generated by Django 3.2.13 on 2022-06-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_payemnts_vendorpayments_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default=None, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='email',
            field=models.EmailField(default=None, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default=None, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone_number',
            field=models.CharField(default=None, max_length=20, null=True, unique=True),
        ),
    ]
